name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create simple static site
        run: |
          # Crear directorio de despliegue
          mkdir -p build
          
          # Copiar archivos estáticos
          cp index.html build/
          cp auction.js build/
          
          # Crear archivo .nojekyll para evitar procesamiento de Jekyll
          touch build/.nojekyll
          
          # Crear página 404 personalizada
          cat > build/404.html << EOL
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>404 - Página no encontrada</title>
              <style>
                  body { font-family: sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; text-align: center; }
                  h1 { color: #0070f3; }
                  .btn { display: inline-block; background: #0070f3; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px; margin: 8px; }
              </style>
          </head>
          <body>
              <h1>404 - Página no encontrada</h1>
              <p>La página que estás buscando no existe o ha sido movida.</p>
              <div>
                  <a href="/AdrianAuctions/" class="btn">Ir al inicio</a>
              </div>
          </body>
          </html>
          EOL
          
          # Crear un robots.txt
          cat > build/robots.txt << EOL
          User-agent: *
          Allow: /
          Sitemap: https://adriangallery.github.io/AdrianAuctions/sitemap.xml
          EOL
          
          # Crear un sitemap básico
          cat > build/sitemap.xml << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
              <url>
                  <loc>https://adriangallery.github.io/AdrianAuctions/</loc>
                  <lastmod>$(date -I)</lastmod>
                  <priority>1.0</priority>
              </url>
          </urlset>
          EOL
          
          # Listar archivos para verificar
          echo "Contenido del directorio de despliegue:"
          ls -la build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          cname: ${{ secrets.CUSTOM_DOMAIN || '' }} 